### PR TITLE
RENO-1153 remove kievit font and tumblr icon

### PR DESCRIPTION
**Pull request by misselbeck**
[Related Jira ticket](https://jira.nypl.org/browse/RENO-1153)

**This PR does the following:**

- Remove Kievit font and fallback to system font to reduce license usage
- Remove Tumblr icon, as that account is no longer maintained

Note: I used this [generic approach](https://css-tricks.com/sans-serif/) for the font stack.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
This looks good. Did you get a chance to try this branch on an NYPL react app? If that's not part of the QA flow for this, that's fine and I can test it.

**Comment by misselbeck** [comment]
If you could test it, that'd be great. Thanks!

**Comment by EdwinGuzman** [comment]
Code-wise, it works locally testing on the homepage app. Just to document, here's prod:
prod
here's the PR branch:
pr

**Comment by misselbeck** [comment]
Thanks, Edwin!

**Comment by EdwinGuzman** [comment]
Just realized that `package.json` wasn't updated with the new `0.5.3` version. I did that and pushed to master. I also just published it to npm so `0.5.3` is now available.

**Pull request merged**
